server:
  port: 80

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: root
      initial-size: 5
      min-idle: 2
      max-active: 10
      max-wait: 6000

  jpa:
    hibernate:
      ddl-auto: update # entity有变化时，更新
    show-sql: true # 日志中显示sql语句
    # 格式化sql
    properties:
      hibernate:
        format_sql: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.origami.springsecurity.domain.entity
  mapper-locations: classpath*:com/origami/springsecurity/mapper/*.xml

token:
  expire:
    second: 3600

